apiVersion: apps/v1
kind: Deployment
metadata:
    name: proje
    namespace: default
    labels:
        app: proje
spec:
    replicas: 3
    selector:
        matchLabels:
            app: proje
    template:
        metadata:
            labels:
                app: proje
        spec:
            containers:
                - name: proje
                  image: alperenibra/main:latest
                  ports:
                      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: nobel-api-service
    namespace: default
spec:
    selector:
        app: proje
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
    type: LoadBalancer
